[package]
name = "zarrebin"
version = "0.1.0"
authors = ["Hosein Khansari <hrk.x11@gmail.com>"]
description = "find files from terminal"
keywords = ["cli"]
license = "GPL-3.0"
readme = "README.md"

[dependencies]
clap = "2.32"
colored = "1.6"